---
 - hosts: seedboxes
   user: root
   vars:
     auth_url: http://requestb.in/u8k0lau8
     munin_hosts:
       - 104.223.1.115
   roles:
     - apt
     - utilities
     - unattended-upgrades
     - munin-node
     - cjdns
     - role: letsencrypt
       letsencrypt_agree_tos: yes
       letsencrypt_agree_eula: yes
     - rtorrent
