---
 - hosts: seedboxes
   user: root
   vars_files:
     - config.yml
   roles:
     - apt
     - utilities
     - unattended-upgrades
     - munin-node
     - cjdns
     - role: letsencrypt
       letsencrypt_agree_tos: yes
       letsencrypt_agree_eula: yes
     - rtorrent
