---
 - hosts: seedboxes
   user: root
   vars_files:
     - config.yml
   roles:
     - apt
     - utilities
     - unattended-upgrades
     - munin-node
     - cjdns
     - role: tor
       tor_distribution_release: "tor-experimental-0.2.7.x-jessie"
       tor_ORPort: 9001
       tor_DirPort: 9030
       tor_ControlPort: 9051
       tor_ExitPolicy: "reject *:*"
       tor_auto_family: true
       tor_ContactInfo: "Finn <finn@janky.solutions> - 1FinnmnefrEHvRw88YfBSpNWPRbe4hnqR3"
       tor_Syslog: "notice"
       tor_BridgeRelay: 1
       tor_Nickname: "{{ ansible_hostname | replace('ns', '') | truncate(7, True, '') }}JankySolution"
       
     - role: letsencrypt
       letsencrypt_agree_tos: yes
       letsencrypt_agree_eula: yes
     - rtorrent
