---
  ## This is a nifty little thing I wrote a while ago that's supposed to peer everyone together.

  # - name: Add an AuthorizedPassword
  #   cjdns:
  #     authorizedPassword:
  #       user: "{{ item }}"
  #       password: "{{ lookup('password', 'AuthorizedPasswords/' + inventory_hostname + '/' + item, length=30) }}"
  #     state: present
  #   with_items: play_hosts
  #   when: item != inventory_hostname
  # - name: Iniate peering
  #   cjdns:
  #     udppeer:
  #       address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}:{{ hostvars[item]['cjdns']['UDPInterface'][0]['port']}}"
  #       data:
  #         publicKey: "{{ hostvars[item]['cjdns']['public_key'] }}"
  #         password: "{{ lookup('password', 'AuthorizedPasswords/' + item + '/' + inventory_hostname, length=30) }}"
  #         hostname: "{{ hostvars[item]['ansible_hostname']}}"
  #         info: "Automatically added by ansible"
  #     state: present
  #   with_items: play_hosts
  #   when: item != inventory_hostname and hostvars[item]['cjdns'] is defined and hostvars[item]['manage_cjdns']

  - name: Add all the defined UDP peers
    cjdns:
      udppeer:
        "{{ item }}"
    with_items: "{{ cjdns_udp_peers }}"
    notify:
      - restart cjdns
