---
  - name: Install fail2ban
    apt: name=fail2ban state=installed

  - name: Generate an ed25519 key
    command: dpkg-reconfigure openssh-server creates=/etc/ssh/ssh_host_ed25519_key

  - name: Template sshd config
    template: src=sshd_config.j2 dest=/etc/ssh/sshd_config validate="sshd -tf %s"
    notify:
      - restart ssh
