---
  - name: reload nginx
    service: name=nginx state=reloaded

  - name: Reload systemd
    command: systemctl daemon-reload

  - name: Restart rtorrent
    service: name=rtorrent state=restarted
